### ISSUE TITLE
[메인페이지 - 이벤트테이블] 디테일 구현 문의드립니다.

### ISSUE THREAD

**Issue by seungyeonchoi** [hshs0409/weltb2b#3]
메인 페이지 이벤트 테이블 구현 시 디테일한 처리가 어려워 문의 남깁니다.

현재 작업은 main_table 브랜치에서 작업하고 있습니다. 구현은 아래 사진처럼 큼직큼직 보이는 것까지 완료되었습니다.
데이터는 data.json 에서 eventData 뽑아왔습니다. 
![image](https://user-images.githubusercontent.com/48347010/99911314-d6ca5400-2d36-11eb-8e00-11397e0b77a8.png)

남은 작업이
1. 컬럼 배경색 보라색으로 만들기
2. hover 했을 때 연보라색 되기
3. 기타 align, 글자색 같은거 설정 입니다.

2번을 구현하고자 [스택오버플로우](https://stackoverflow.com/questions/15643037/how-do-i-change-the-hover-over-color-for-a-hover-over-table-in-bootstrap) 을 참고하여 
`
.table-hover tbody tr:hover td, .table-hover tbody tr:hover th {
  background-color: #color;
}
`
를 설정하면 된다고 알게되었습니다.

근데 중요한건!!! 저걸 어디다가 적어야할지 모르겠습니다....
조언부탁드립니다...!

**Comment by hshs0409** [comment]
우선 Component에 EventTable.css 만드시고
EventTable.js 에
import "./EventTable.css "  하는식으로 해야 할 것 같습니다.
antd에서 Column Header 스타일 지정 해주는게 없네요...

```
.editable-cell {
  position: relative;
}

.editable-cell-value-wrap {
  padding: 5px 12px;
  cursor: pointer;
}

.editable-row:hover .editable-cell-value-wrap {
  border: 1px solid #d9d9d9;
  border-radius: 4px;
  padding: 4px 11px;
}
```

이런식으로 antd docs에서도 지정해주고 있어서 아마 저 css에 파일에다가 클래스네임 선언하고 지정해줘야 할 것 같습니다.
4개 칼럼에 똑같은 className 지정해주고
해당 클래스네임에 hover시 연보라색 지정도 가능할것같습니다.
글자색 align도 css파일 내에서 처리 가능한 듯 싶습니다.
아니면 children의 style 내에서도 처리 가능합니다.

**Comment by seungyeonchoi** [comment]
네 확인했습니다. 조언 감사합니다!!!!!!!!!!!!
